# Generated by Django 5.1 on 2024-08-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.TextField()),
                ('account_number', models.TextField()),
                ('customer_name', models.TextField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_date', models.DateField()),
            ],
        ),
    ]
